- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env','HOME') }}/personal"
  pre_tasks:
  - name: update cache
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
    - core
    - install
  tasks: 
  - include: tasks/ssh.yml
  - include: tasks/nvim-setup.yml
  - include: tasks/node-setup.yml
  - include: tasks/npm-packages.yml
  - include: tasks/core-setup.yml
  - include: tasks/dotfiles.yml
    
 
