- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: false
  community.general.homebrew:
    name: [ "cmake","automake", "pkg-config", "libpthread-stubs"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: false
  community.general.homebrew:
    name: [ "lua@5.1", "unzip", "libtool", "gettext","ripgrep"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: false
  community.general.homebrew:
    name: [  "htop", "ccache" ]
  tags:
    - install
    - core

- name: Install Tmux
  become: false
  community.general.homebrew:
    name: ["tmux"]
  tags:
    - install
    - core
    - tmux
