- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  community.general.homebrew:
    name: [ "cmake", "pkg-config", "libpthread-stubs"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  community.general.homebrew:
    name: [ "lua@5.1", "unzip", "libtool", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  community.general.homebrew:
    name: [  "htop", "ccache" ]
  tags:
    - install
    - core


